http:
  middlewares:
    this_is_my_custom_middleware:
      headers:
        customRequestHeaders:
          X-Dummy-Request-Header: "traefik"
        customResponseHeaders:
          X-Dummy-Response-Header: "traefik"